# site settings

title: Mohammad Amin Asadi
description: Mohammad Amin Asadi Portfolio
taglong: Mohammad Amin Asadi Portfolio
tagshort: Asadi Portfolio
url: /assets/jpg/MohammadـAminـAsadi-ComputerـVision.pdf
baseurl: ""
permalink: pretty
repo: https://github.com/prankshtain/prankshtain.github.io

# author settings

author:
  name: Mohammad Amin Asadi
  email: username@domain.com
photo: /assets/jpg/Mohammad_Amin_Asadi.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
